// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Album is the predicate function for album builders.
type Album func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// NotificationConfig is the predicate function for notificationconfig builders.
type NotificationConfig func(*sql.Selector)

// Picture is the predicate function for picture builders.
type Picture func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
