// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	ent "github.com/depromeet/everybody-backend/rest-api/ent"
	mock "github.com/stretchr/testify/mock"
)

// PushAdapter is an autogenerated mock type for the PushAdapter type
type PushAdapter struct {
	mock.Mock
}

// Send provides a mock function with given fields: title, content, device
func (_m *PushAdapter) Send(title string, content string, device *ent.Device) error {
	ret := _m.Called(title, content, device)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *ent.Device) error); ok {
		r0 = rf(title, content, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
