service: everybody-media-procesor
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7 # 3.8버전부터는 opencv나 numpy를 위한 dependency가 완전히 보장되지 않는 linux image를 쓰게 됨
  lambdaHashingVersion: '20201221'
  region: ap-northeast-2
  stage: ${env:EVERYBODY_STAGE,'dev'}
  profile: depromeet-everybody
#  TODO: internal하게 everybody-api-gateway만이 호출할 수 있게
#  endpointType: PRIVATE
  tracing:
    lambda: true
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

functions:
  hello:
    handler: hello_handler.handle
# PythonRequirementLambda로 레이어를 이용하려는 경우에만 설정
#    layers:
#      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - httpApi:
          path: /
          method: get
  panorama:
    handler: generate_panorama.handler.handle
#    layers:
#      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - httpApi:
          path: /panorama
          method: get
  video:
    handler: generate_video.handler.handle
#    layers:
#      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - httpApi:
          path: /video
          method: get
  thumbnail-generator:
    handler: generate_thumbnail.handler.handle
    description: INPUT_BUCKET/INPUT_OBJECT_KEY 경로에 이미지 업로드 시에 OUTPUT_BUCKET/OUTPUT_OBJECT_KEY 경로에 썸네일을 생성
    events:
      - s3:
          bucket: everybody-upload-original-dev-1
          event: s3:ObjectCreated:*
          rules:
            - prefix: original/
          # S3 버킷 관리를 serverless가 수행할 경우 버킷이 통째로 날아갈 수도 있다.
          # 따라서 existing bucket으로 정의한다.
          existing: true

plugins:
  # 로컬에서 http로 핸들러를 트리거하기 위함
  - serverless-offline
  # third party dependency를 위함
  - serverless-python-requirements

package:
  patterns:
    # numpy나 open cv때문에 직접 빌드해야한다.
    - '!venv/**'

custom:
  pythonRequirements:
#    # docker로 직접 pip build를 해야할 수 있음 numpy나 opencv 같은 것들은 (window나 mac에서는 다르게 빌드될 수 있음)
    dockerizePip: true
    # layer에 불필요한 애들이 다 포함되어버리는 것 같은데 venv나 node_modules 같은 거...
#    layer: true
    # zip 안해도 되나...
#    zip: true

