apiGw:
  port: 8080
  healthCheckPath: /health*
  authEnable: false

db:
  mySql:
    host: localhost
    port: 3306
    databaseName: everybody
    user: admin
    password: admin

targetServer:
  restApi: 
    address: http://localhost:8080/health
    prefix: restapi