apiGw:
  port: 8080
  healthCheckPath: /health
  authEnable: true
  accessTokenSecret: 123123

db:
  mySql:
    host: localhost
    port: 3306
    databaseName: everybody
    user: root
    password: root

targetServer:
  restApi: 
    address: http://localhost:8080/health
    prefix: restapi
  lambdaImageUpload:
    address: http://localhost:8080/health
    method: POST