// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depromeet/everybody-backend/rest-api/ent/notificationconfig"
	"github.com/depromeet/everybody-backend/rest-api/ent/user"
)

// NotificationConfigCreate is the builder for creating a NotificationConfig entity.
type NotificationConfigCreate struct {
	config
	mutation *NotificationConfigMutation
	hooks    []Hook
}

// SetMonday sets the "monday" field.
func (ncc *NotificationConfigCreate) SetMonday(b bool) *NotificationConfigCreate {
	ncc.mutation.SetMonday(b)
	return ncc
}

// SetNillableMonday sets the "monday" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableMonday(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetMonday(*b)
	}
	return ncc
}

// SetTuesday sets the "tuesday" field.
func (ncc *NotificationConfigCreate) SetTuesday(b bool) *NotificationConfigCreate {
	ncc.mutation.SetTuesday(b)
	return ncc
}

// SetNillableTuesday sets the "tuesday" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableTuesday(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetTuesday(*b)
	}
	return ncc
}

// SetThursday sets the "thursday" field.
func (ncc *NotificationConfigCreate) SetThursday(b bool) *NotificationConfigCreate {
	ncc.mutation.SetThursday(b)
	return ncc
}

// SetNillableThursday sets the "thursday" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableThursday(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetThursday(*b)
	}
	return ncc
}

// SetFriday sets the "friday" field.
func (ncc *NotificationConfigCreate) SetFriday(b bool) *NotificationConfigCreate {
	ncc.mutation.SetFriday(b)
	return ncc
}

// SetNillableFriday sets the "friday" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableFriday(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetFriday(*b)
	}
	return ncc
}

// SetSaturday sets the "saturday" field.
func (ncc *NotificationConfigCreate) SetSaturday(b bool) *NotificationConfigCreate {
	ncc.mutation.SetSaturday(b)
	return ncc
}

// SetNillableSaturday sets the "saturday" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableSaturday(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetSaturday(*b)
	}
	return ncc
}

// SetSunday sets the "sunday" field.
func (ncc *NotificationConfigCreate) SetSunday(b bool) *NotificationConfigCreate {
	ncc.mutation.SetSunday(b)
	return ncc
}

// SetNillableSunday sets the "sunday" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableSunday(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetSunday(*b)
	}
	return ncc
}

// SetPreferredTimeHour sets the "preferred_time_hour" field.
func (ncc *NotificationConfigCreate) SetPreferredTimeHour(s string) *NotificationConfigCreate {
	ncc.mutation.SetPreferredTimeHour(s)
	return ncc
}

// SetNillablePreferredTimeHour sets the "preferred_time_hour" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillablePreferredTimeHour(s *string) *NotificationConfigCreate {
	if s != nil {
		ncc.SetPreferredTimeHour(*s)
	}
	return ncc
}

// SetPreferredTimeMinute sets the "preferred_time_minute" field.
func (ncc *NotificationConfigCreate) SetPreferredTimeMinute(s string) *NotificationConfigCreate {
	ncc.mutation.SetPreferredTimeMinute(s)
	return ncc
}

// SetNillablePreferredTimeMinute sets the "preferred_time_minute" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillablePreferredTimeMinute(s *string) *NotificationConfigCreate {
	if s != nil {
		ncc.SetPreferredTimeMinute(*s)
	}
	return ncc
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (ncc *NotificationConfigCreate) SetLastNotifiedAt(t time.Time) *NotificationConfigCreate {
	ncc.mutation.SetLastNotifiedAt(t)
	return ncc
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableLastNotifiedAt(t *time.Time) *NotificationConfigCreate {
	if t != nil {
		ncc.SetLastNotifiedAt(*t)
	}
	return ncc
}

// SetIsActivated sets the "is_activated" field.
func (ncc *NotificationConfigCreate) SetIsActivated(b bool) *NotificationConfigCreate {
	ncc.mutation.SetIsActivated(b)
	return ncc
}

// SetNillableIsActivated sets the "is_activated" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableIsActivated(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetIsActivated(*b)
	}
	return ncc
}

// SetID sets the "id" field.
func (ncc *NotificationConfigCreate) SetID(i int) *NotificationConfigCreate {
	ncc.mutation.SetID(i)
	return ncc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ncc *NotificationConfigCreate) SetUserID(id int) *NotificationConfigCreate {
	ncc.mutation.SetUserID(id)
	return ncc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableUserID(id *int) *NotificationConfigCreate {
	if id != nil {
		ncc = ncc.SetUserID(*id)
	}
	return ncc
}

// SetUser sets the "user" edge to the User entity.
func (ncc *NotificationConfigCreate) SetUser(u *User) *NotificationConfigCreate {
	return ncc.SetUserID(u.ID)
}

// Mutation returns the NotificationConfigMutation object of the builder.
func (ncc *NotificationConfigCreate) Mutation() *NotificationConfigMutation {
	return ncc.mutation
}

// Save creates the NotificationConfig in the database.
func (ncc *NotificationConfigCreate) Save(ctx context.Context) (*NotificationConfig, error) {
	var (
		err  error
		node *NotificationConfig
	)
	ncc.defaults()
	if len(ncc.hooks) == 0 {
		if err = ncc.check(); err != nil {
			return nil, err
		}
		node, err = ncc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotificationConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ncc.check(); err != nil {
				return nil, err
			}
			ncc.mutation = mutation
			if node, err = ncc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ncc.hooks) - 1; i >= 0; i-- {
			if ncc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ncc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ncc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ncc *NotificationConfigCreate) SaveX(ctx context.Context) *NotificationConfig {
	v, err := ncc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncc *NotificationConfigCreate) Exec(ctx context.Context) error {
	_, err := ncc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncc *NotificationConfigCreate) ExecX(ctx context.Context) {
	if err := ncc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ncc *NotificationConfigCreate) defaults() {
	if _, ok := ncc.mutation.Monday(); !ok {
		v := notificationconfig.DefaultMonday
		ncc.mutation.SetMonday(v)
	}
	if _, ok := ncc.mutation.Tuesday(); !ok {
		v := notificationconfig.DefaultTuesday
		ncc.mutation.SetTuesday(v)
	}
	if _, ok := ncc.mutation.Thursday(); !ok {
		v := notificationconfig.DefaultThursday
		ncc.mutation.SetThursday(v)
	}
	if _, ok := ncc.mutation.Friday(); !ok {
		v := notificationconfig.DefaultFriday
		ncc.mutation.SetFriday(v)
	}
	if _, ok := ncc.mutation.Saturday(); !ok {
		v := notificationconfig.DefaultSaturday
		ncc.mutation.SetSaturday(v)
	}
	if _, ok := ncc.mutation.Sunday(); !ok {
		v := notificationconfig.DefaultSunday
		ncc.mutation.SetSunday(v)
	}
	if _, ok := ncc.mutation.IsActivated(); !ok {
		v := notificationconfig.DefaultIsActivated
		ncc.mutation.SetIsActivated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ncc *NotificationConfigCreate) check() error {
	if _, ok := ncc.mutation.Monday(); !ok {
		return &ValidationError{Name: "monday", err: errors.New(`ent: missing required field "monday"`)}
	}
	if _, ok := ncc.mutation.Tuesday(); !ok {
		return &ValidationError{Name: "tuesday", err: errors.New(`ent: missing required field "tuesday"`)}
	}
	if _, ok := ncc.mutation.Thursday(); !ok {
		return &ValidationError{Name: "thursday", err: errors.New(`ent: missing required field "thursday"`)}
	}
	if _, ok := ncc.mutation.Friday(); !ok {
		return &ValidationError{Name: "friday", err: errors.New(`ent: missing required field "friday"`)}
	}
	if _, ok := ncc.mutation.Saturday(); !ok {
		return &ValidationError{Name: "saturday", err: errors.New(`ent: missing required field "saturday"`)}
	}
	if _, ok := ncc.mutation.Sunday(); !ok {
		return &ValidationError{Name: "sunday", err: errors.New(`ent: missing required field "sunday"`)}
	}
	if _, ok := ncc.mutation.IsActivated(); !ok {
		return &ValidationError{Name: "is_activated", err: errors.New(`ent: missing required field "is_activated"`)}
	}
	return nil
}

func (ncc *NotificationConfigCreate) sqlSave(ctx context.Context) (*NotificationConfig, error) {
	_node, _spec := ncc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ncc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (ncc *NotificationConfigCreate) createSpec() (*NotificationConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationConfig{config: ncc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: notificationconfig.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: notificationconfig.FieldID,
			},
		}
	)
	if id, ok := ncc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ncc.mutation.Monday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notificationconfig.FieldMonday,
		})
		_node.Monday = value
	}
	if value, ok := ncc.mutation.Tuesday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notificationconfig.FieldTuesday,
		})
		_node.Tuesday = value
	}
	if value, ok := ncc.mutation.Thursday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notificationconfig.FieldThursday,
		})
		_node.Thursday = value
	}
	if value, ok := ncc.mutation.Friday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notificationconfig.FieldFriday,
		})
		_node.Friday = value
	}
	if value, ok := ncc.mutation.Saturday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notificationconfig.FieldSaturday,
		})
		_node.Saturday = value
	}
	if value, ok := ncc.mutation.Sunday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notificationconfig.FieldSunday,
		})
		_node.Sunday = value
	}
	if value, ok := ncc.mutation.PreferredTimeHour(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notificationconfig.FieldPreferredTimeHour,
		})
		_node.PreferredTimeHour = value
	}
	if value, ok := ncc.mutation.PreferredTimeMinute(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notificationconfig.FieldPreferredTimeMinute,
		})
		_node.PreferredTimeMinute = value
	}
	if value, ok := ncc.mutation.LastNotifiedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notificationconfig.FieldLastNotifiedAt,
		})
		_node.LastNotifiedAt = value
	}
	if value, ok := ncc.mutation.IsActivated(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: notificationconfig.FieldIsActivated,
		})
		_node.IsActivated = value
	}
	if nodes := ncc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationconfig.UserTable,
			Columns: []string{notificationconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_notification_config = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationConfigCreateBulk is the builder for creating many NotificationConfig entities in bulk.
type NotificationConfigCreateBulk struct {
	config
	builders []*NotificationConfigCreate
}

// Save creates the NotificationConfig entities in the database.
func (nccb *NotificationConfigCreateBulk) Save(ctx context.Context) ([]*NotificationConfig, error) {
	specs := make([]*sqlgraph.CreateSpec, len(nccb.builders))
	nodes := make([]*NotificationConfig, len(nccb.builders))
	mutators := make([]Mutator, len(nccb.builders))
	for i := range nccb.builders {
		func(i int, root context.Context) {
			builder := nccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nccb *NotificationConfigCreateBulk) SaveX(ctx context.Context) []*NotificationConfig {
	v, err := nccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nccb *NotificationConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := nccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nccb *NotificationConfigCreateBulk) ExecX(ctx context.Context) {
	if err := nccb.Exec(ctx); err != nil {
		panic(err)
	}
}
