// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/depromeet/everybody-backend/rest-api/ent/notificationconfig"
	"github.com/depromeet/everybody-backend/rest-api/ent/predicate"
)

// NotificationConfigDelete is the builder for deleting a NotificationConfig entity.
type NotificationConfigDelete struct {
	config
	hooks    []Hook
	mutation *NotificationConfigMutation
}

// Where appends a list predicates to the NotificationConfigDelete builder.
func (ncd *NotificationConfigDelete) Where(ps ...predicate.NotificationConfig) *NotificationConfigDelete {
	ncd.mutation.Where(ps...)
	return ncd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ncd *NotificationConfigDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ncd.hooks) == 0 {
		affected, err = ncd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotificationConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ncd.mutation = mutation
			affected, err = ncd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ncd.hooks) - 1; i >= 0; i-- {
			if ncd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ncd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ncd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncd *NotificationConfigDelete) ExecX(ctx context.Context) int {
	n, err := ncd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ncd *NotificationConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: notificationconfig.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: notificationconfig.FieldID,
			},
		},
	}
	if ps := ncd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ncd.driver, _spec)
}

// NotificationConfigDeleteOne is the builder for deleting a single NotificationConfig entity.
type NotificationConfigDeleteOne struct {
	ncd *NotificationConfigDelete
}

// Exec executes the deletion query.
func (ncdo *NotificationConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := ncdo.ncd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ncdo *NotificationConfigDeleteOne) ExecX(ctx context.Context) {
	ncdo.ncd.ExecX(ctx)
}
