db:
  mySql:
    host: localhost
    port: 3306
    databaseName: everybody
    user: admin
    password: admin

aws:
  profile: profileName
  bucket: bucketName
  region: regionName
# 환경에 맞춰
# local.yml 혹은 dev.yml 등을 정의해주세요
publicDriveRootURL: https://some.cloudfront.net or https://some.s3.com
imageRootURL: https://some.cloudfront.net
imagePublicKeyID: ABCDEFGHIJK
imagePrivateKey: |
  -----BEGIN RSA PRIVATE KEY-----
  ...
  -----END RSA PRIVATE KEY-----

push:
  fcm:
    # 절대 경로
    serviceAccountFile: /home/everybody-backend/rest-api/config/service-account-dev.yml

# 눈바디 독려 알림을 보내는 루틴
notifyRoutine:
  enabled: false
  # 루틴을 반복할 떄의 interval. 초 단위
  interval: 60 # e.g. 60 = 60초


