db:
  mySql:
    host: localhost
    port: 3306
    databaseName: everybody
    user: admin
    password: admin

aws:
  profile: profileName
  bucket: bucketName
  region: regionName
# 환경에 맞춰
# local.yml 혹은 dev.yml 등을 정의해주세요
