sample_data = {
    'version': '2.0',
    'routeKey': 'POST /video',
    'rawPath': '/video',
    'rawQueryString': '',
    'cookies': [],
    'headers': {
        'user': '50',
        'Content-Type': 'application/json',
        'User-Agent': 'PostmanRuntime/7.28.4',
        'Accept': '*/*',
        'Cache-Control': 'no-cache',
        'Postman-Token': 'd0967107-9e05-4115-99a8-e645a751e860',
        'Host': 'localhost:3000',
        'Accept-Encoding': 'gzip,deflate,br',
        'Connection': 'keep-alive',
        'Content-Length': '178'
    },
    'queryStringParameters': None,
    'requestContext': {'accountId': 'offlineContext_accountId',
    'apiId': 'offlineContext_apiId',
    'authorizer': {'jwt': {}},
    'domainName': 'offlineContext_domainName',
    'domainPrefix': 'offlineContext_domainPrefix',
    'http': {'method': 'POST',
    'path': '/video',
    'protocol': 'HTTP/1.1',
    'sourceIp': '127.0.0.1',
    'userAgent': 'PostmanRuntime/7.28.4'},
    'requestId': 'offlineContext_resourceId',
    'routeKey': 'POST /video',
    'stage': '$default',
    'time': '24/Dec/2021:10:00:15 +0900',
    'timeEpoch': 1640307615930},
    'body': '[\r\n    {\r\n        "key": "first-picture-object-key"\r\n    },\r\n    {\r\n        "key": "second-picture-object-key"\r\n    },\r\n    {\r\n        "key": "third-picture-object-key"\r\n    }\r\n]',
    'pathParameters': None,
    'isBase64Encoded': False
}