service: everybody-video2
frameworkVersion: '2'

provider:
  name: aws
#  runtime: python3.7 # 3.8버전부터는 opencv나 numpy를 위한 dependency가 완전히 보장되지 않는 linux image를 쓰게 됨
  lambdaHashingVersion: '20201221'
  region: ap-northeast-2
  stage: ${env:EVERYBODY_STAGE,'dev'}
  profile: depromeet-everybody
#  TODO: internal하게 everybody-api-gateway만이 호출할 수 있게
#  endpointType: PRIVATE
  tracing:
    lambda: true
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  # lambda custom base image: https://www.serverless.com/blog/container-support-for-lambda
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      everybody:
        path: './'
functions:
  video:
    description: 전달받은 key로 OpenCV와 numpy를 바탕으로 영상 제작 후 제공
    image:
      name: everybody
    events:
      - httpApi:
          path: /video
          method: post

plugins:
  - serverless-offline
package:
  patterns:
    # numpy나 open cv때문에 직접 빌드해야한다.
    - '!venv/**'
