name: deploy rest-api
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+09:00"

    - name: copy config file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp s3://${{ secrets.SECRET_BUCKET }}/dev.yml rest-api/config/

    - name: build rest-api
      run: |
        GOOS=linux GOARCH=amd64 go build -o rest main.go
      working-directory: rest-api

    - name: prepare to deploy
      run: |
        mkdir -p deploy
        cp rest deploy/rest
        cp -r Procfile deploy/Procfile
        cp -r .ebextensions deploy/.ebextensions
        cp -r config/dev.yml deploy/config/dev.yml
        cd deploy && zip -r deploy.zip .
      working-directory: rest-api

      # ref) https://github.com/marketplace/actions/beanstalk-deploy
    - name: deploy to eb
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # secrets.APPLICATION_NAME,ENVIRONMENT_NAME 이렇게 하자...
        application_name: everybody
        environment_name: Everybody-dev
        version_label: app-${{ steps.current-time.outputs.formattedTime }}
        region: ap-northeast-2
        deployment_package: rest-api/deploy/deploy.zip
        # wait_for_environment_recovery: 200
